<a href="https://colab.research.google.com/github/zackerazx/MXB107/blob/main/notebooks/Week_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Week 4: Law of Total Probability and Bayes Rule**

```
.------------------------------------.
|   __  ____  ______  _  ___ _____   |
|  |  \/  \ \/ / __ )/ |/ _ \___  |  |
|  | |\/| |\  /|  _ \| | | | | / /   |
|  | |  | |/  \| |_) | | |_| |/ /    |
|  |_|  |_/_/\_\____/|_|\___//_/     |
'------------------------------------'

```
This week we'll do some more pen-and-paper questions on the law of total probability and Bayes' rule. We'll also do some probability examples in R.

## **Pre-Configurating the Notebook**

### **Switching to the R Kernel on Colab**

By default, Google Colab uses Python as its programming language. To use R instead, you’ll need to manually switch the kernel by going to **Runtime > Change runtime type**, and selecting R as the kernel. This allows you to run R code in the Colab environment.

However, our notebook is already configured to use R by default. Unless something goes wrong, you shouldn’t need to manually change runtime type.

### **Importing Required Packages**
**Run the following lines of code**:

In [1]:
#Do not modify

setwd("/content")

# Remove `MXB107-Notebooks` if exists,
if (dir.exists("MXB107-Notebooks")) {
  system("rm -rf MXB107-Notebooks")
}

# Fork the repository
system("git clone https://github.com/ArwenNugteren/MXB107-Notebooks")

# Change working directory to "MXB107-Notebooks"
setwd("MXB107-Notebooks")

#
invisible(source("R/preConfigurated.R"))

Loading required package: ggplot2

Loading required package: dplyr


Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union


Loading required package: tidyr

Loading required package: stringr

Loading required package: magrittr


Attaching package: ‘magrittr’


The following object is masked from ‘package:tidyr’:

    extract


Loading required package: IRdisplay

Loading required package: png

Warning message in library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE, :
“there is no package called ‘png’”
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

Loading required package: grid

Loading required package: knitr

Loading required package: jpeg

Warning message in library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE, :
“there is no package called ‘jpeg’”
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

**Do not modify the following**

In [2]:
if (!require("testthat")) install.packages("testthat"); library("testthat")

test_that("Test if all packages have been loaded", {

  expect_true(all(c("ggplot2", "tidyr", "dplyr", "stringr", "magrittr", "knitr") %in% loadedNamespaces()))

})

Loading required package: testthat


Attaching package: ‘testthat’


The following objects are masked from ‘package:magrittr’:

    equals, is_less_than, not

Test passed with 1 success 🥇.

# Warm-up question
A class has 40% STEM majors, 60% non-STEM majors.

* STEM: 70% drink coffee

* Non-STEM: 30% drink coffee

Question:
What is the overall probability that a random student drinks coffee?

Given a student walks into class holding a coffee, is it more likely that they are a STEM major or a non-STEM major? Can you work out the probabilities of each?

# Pen-and-paper questions

## Question 1
Weather bureau records show that for a certain type of weather pattern, the chance of rain at dam A is 40\% and at dam B is 75\%, and the chance of rain at least one of the dams is 80\%. If this weather pattern brings rain to dam B, what is the chance it will also bring rain to dam A?

<details>
<summary>▶️ Click to show the solution</summary>

Let $R_A$ be the event that it rains at dam A and $R_B$ be the event that it rains at dam B. Then
			$$ Pr(R_A) = 0.4,\, Pr(R_B)=0.75,\,Pr(R_A\cup R_B)=0.8 $$

We want
			$$\begin{align*}
				Pr(R_A|R_B) &= \frac{Pr(R_AR_B)}{Pr(R_B)} \quad  \text{ conditional rule} \\
				&= \frac{Pr(R_A)+Pr(R_B)-Pr(R_A\cup R_B)}{Pr(R_B)} \quad \text{ addition rule} \\
				&=\frac{0.4+0.75-0.8}{0.75}\\
				&\approx  0.467.
			\end{align*} $$

</details>

### Question 2
Hospital Patients' Survey Data is claimed that based on some clinical trials:

* there is a 15\% chance of experiencing depression problems known as Seasonal Affective Disorder (SAD),
- there is a 28\% chance of experiencing heart disease known as Angina,
- and there is a 8\% chance of experiencing both side effects.



a) Suppose that the patient experiences SAD; what is the probability that the patient will also experience Angina?


b) Suppose the drug induces Angina in a patient; what is the probability that it also induces SAD?


c)  Suppose the drug induces Angina in a patient; what is the probability that it does not induce SAD?

d) Suppose that the patient doesn’t experience SAD; what is the probability that the patient will not experience Angina?

<details>
<summary>▶️ Click to show the solution</summary>

Let $S$ be the event that a patient experiences SAD and $A$ be the event that a patient experiences Angina. We know that
			$$Pr(A) = 0.28,\quad Pr(S)=0.15,\quad Pr(A S) = 0.08$$

a)  \begin{align*}
				Pr(A|S) &=\frac{Pr(A S)}{Pr(S)} \quad \text{ conditional probability} \\
				&=\frac{0.08}{0.15}\\
				&\approx 0.53.
			\end{align*}


b) \begin{align*}
				Pr(S|A) &= \frac{Pr(S A)}{Pr(A)} \quad \text{ conditional probability} \\
				&= \frac{0.08}{0.28}\\
				&\approx  0.2857.
			\end{align*}


c) \begin{align*}
				Pr(\overline{S}|A) &= 1-Pr(S|A) \quad \text{ complement rule}\\
				&\approx  1-0.2857\\
				&= 0.7143.
			\end{align*}


d) \begin{align*}
				Pr(\overline{A}|\overline{S}) &= \frac{Pr(\overline{S}\:\: \overline{A})}{Pr(\overline{S})} & \text{conditional rule}\\
				&= \frac{1 - Pr(A\cup S)}{1 - Pr(S)} & \text{De Morgan's law} \\
				&= \frac{1-Pr(A)-Pr(S)+Pr(A S)}{1-0.15} & \text{addition rule} \\
				&=\frac{1-0.28-0.15+0.08}{0.85}\\
				&\approx  0.7647
			\end{align*}



</details>

## Question 3
In a water quality monitoring schedule, water samples from dams are tested for a particular strain of bacteria which is found in 2\% of dam water. The test for this strain is 95\% reliable when the bacteria are present, and 90\% reliable when they are not.

a)  If the test says that the bacteria are present in a sample, what is the probability that the bacteria are not present?

b)  If the test says that the bacteria are not present in a sample, what is the probability that the bacteria are present?

c) The testing is extended to include sources of water that feed into dams. In such sources it is known that the bacterial strain occurs in 3\% of the water. Twice as much testing is carried out for dams as for the other sources. In what proportions of tests that return a negative result (that is, that say the bacteria are not present) are the bacteria actually present?

<details>
<summary>▶️ Click to show the solution</summary>

Let $B$ be the event that bacteria is present, and let $T$ be the event that the test says bacteria is present.

Probabilities:
			$$P(B) = 0.02,\, P(T|B)=0.95,\, P(T|\overline{B})=0.1.$$

a) \begin{align*}
				P(\overline{B}|T) &= \frac{P(T|\overline{B})P(\overline{B})}{P(T)}&&\text{ Bayes' rule} \\
					&=\frac{P(T|\overline{B})P(\overline{B})}{P(T|\overline{B})P(\overline{B})+P(T|B)P(B)}&& \text{law of total probability} \\
					&= \frac{0.1\times0.98}{0.1\times0.98+0.95\times0.02}\\
					&\approx 0.8376.
				\end{align*}

b)  Note from the complement rule that $P(\overline{T})=1-P(T) = 1-0.117 = 0.883$
			\begin{align*}
				P(B|\overline{T}) &= \frac{P(\overline{T}|B)P(B)}{P(\overline{T})}&&\text{ Bayes' rule}\\
					&= \frac{0.05\times0.02}{0.883}\\
					&\approx 0.00113
			\end{align*}

c)  Let D be the event that water comes from the dam. Then

$$P(D)=2/3, \text{ and } P(\overline{D})=1/3.$$

To calculate $P(B)$ use the law to total probability.

$$P(B) = P(B|D)P(D)+P(B|\overline{D})P(\overline{D}) = 0.02\times2/3+0.03\times1/3\approx0.0233$$

Now we can determine the probability that the bacteria are present when the test says they are not present.

\begin{align*}
					P(B|\overline{T}) &= \frac{P(\overline{T}|B)P(B)}{P(\overline{T})}&&\text{ Bayes' rule}\\
						&= \frac{P(\overline{T}|B)P(B)}{P(\overline{T}|B)P(B)+P(\overline{T}|\overline{B})P(\overline{B})}&&\text{ law of total probability} \\
						&\approx \frac{0.05\times0.0233}{0.05\times0.0233+0.9\times(1-0.0233)}\\
						&\approx 0.00132.
				\end{align*}


</details>

## Question 4
A new marketing campaign runs advertisements in newspapers for an existing product that currently (that is, before the campaign) has 5\% of the market. Based on newspaper circulation figures and previous survey information, the marketing company states that the probability that an arbitrary person sees the ads is 60\%. During the newspaper ads campaign, the buyers of the product were asked if they'd seen the ads, 75\% replied that they had. Assume that for those who did not see the ads, the probability of buying the product is still 5\%.

a) Show that the probability that a person who saw the ads buys the product is exactly 10%.

b) Why is $Pr(B)\neq 0.05$, where $B$ is the event "customer buys product"?

<details>
<summary>▶️ Click to show the solution</summary>
Let $S$ be the event of a customer seeing the product and let $B$ be the event that a customer buys the product.

Given Probabilities:
			\begin{align*}
				P(S) &= 0.6 &
				P(S|B) &= 0.75\\
				P(B|\overline{S}) &= 0.05 &
				P(B|S) &= 0.1
			\end{align*}

a)
				\begin{align*}
					P(B|S) &= \frac{P(S|B)P(B)}{P(S)} && \text{ Bayes' rule}\\
					P(B) &= P(BS)+P(B\overline{S}) &&\text{ law of total probability} \\
						&= P(B|S)P(S)+P(B|\overline{S})P(\overline{S})\\
						&= 0.6P(B|S)+0.02\\
					P(B|S) &=\frac{0.75(0.6P(B|S)+0.02)}{0.6}\\
					P(B|S)-0.75P(B|S) &= \frac{0.75\times0.02}{0.6}\\
					P(B|S) &= \frac{0.025}{0.25}\\
						&= 0.1
				\end{align*}


b) The reason why $Pr(B)\neq 0.05$ during or after the campaign is because prior to the campaign the entire population had "not seen the ad". During and after the campaign, the population is divided into those who have not seen the ad and those who have seen the ad and those who have seen the ad, will have an increased probability of buying the product. We should expect $Pr(B)>0.05$ after the campaign, and that is exactly what we see with the law of total probability ($Pr(B)=0.08$).


</details>

# Probability in R

### **Question 1**

Three (fair) six-sided dice are rolled and their values summed. Calculate the probability of observing exactly two dice showing the same value and the third showing a different value.

We can generate all possible outcomes of rolling three 6-sided dice using the `expand.grid()` function. This results is a `data.frame`, assigned to `outcomes`.

In [3]:
die1 = die2 = die3 = 1:6 # this creates a vector of the values 1-6
outcomes = expand.grid(die1, die2, die3) # this makes every possible combination and calls them variables (Var)

# head() means we only want to see the first X rows of a large table
head(outcomes, 10)

   Var1 Var2 Var3
1  1    1    1
2  2    1    1
3  3    1    1
4  4    1    1
5  5    1    1
6  6    1    1
7  1    2    1
8  2    2    1
9  3    2    1
10 4    2    1

##### **Question 1.1**

Rename `Var1`, `Var2`, and `Var3` columns to `Die1`, `Die2`, and `Die3`.

Hint: use the `colnames()` function to set the column names to a vector of names.

In [26]:
colnames(outcomes)<- c('Die1', 'Die2', 'Die3')

<details>
<summary>▶️ Click to show the solution</summary>

```r
colnames(outcomes) <- c("Die1", "Die2", "Die3")

# check it worked
head(outcomes, 10)
```

</details>

##### **The `ifelse()` Function**

The `ifelse(test, yes, no)` evaluates the logical or comparision expression in `test`. If `test` is `true`, the value in `yes` is returned. Otherwise, return the value in `no`.

In [19]:
ifelse(3>5, "Aha!", "Voila!")

[1] "Voila!"

`test` can be a vector operation.

In [5]:
ifelse(c(1,2,3,4,5)>3, "Aha!", "Voila!")

[1] "Voila!" "Voila!" "Voila!" "Aha!"   "Aha!"

We can create a new column named `Die1GreaterThan3` where value is 1 if `Die1 > 3` and 0 otherwise. We can create new columns by using the `$` sign.

In [27]:
outcomes$Die1GreaterThan3 = ifelse(outcomes$Die1 > 3, 1, 0)

# check we got it right
head(outcomes, 10)

   Die1 Die2 Die3 Die1GreaterThan3
1  1    1    1    0
2  2    1    1    0
3  3    1    1    0
4  4    1    1    1
5  5    1    1    1
6  6    1    1    1
7  1    2    1    0
8  2    2    1    0
9  3    2    1    0
10 4    2    1    1

##### **Question 1.2**

Create a new column named `Satisfied` where value is 1 if we observe exactly two dice showing the same value and the third showing a different value and 0 otherwise. We can express multiple **or** conditions using the pipe symbol `|`. We can express "logically equal" using `==` and not equal using `!=`.

<details>
<summary>▶️ Click to show hint</summary>

We need `Die1 == Die2` and `Die1 != Die3` **or** `Die2 == Die3` and `Die1 != Die3`, **or** `Die1 == Die3` and `Die1 != Die2`.

</details>

In [33]:
outcomes$Satisfied = ifelse(outcomes$Die1 == outcomes$Die2 & outcomes$Die1 != outcomes$Die3|
                            outcomes$Die1 == outcomes$Die3 & outcomes$Die1 != outcomes$Die2|
                            outcomes$Die2 == outcomes$Die3 & outcomes$Die1 != outcomes$Die2, 1,0)
head(outcomes,10)

   Die1 Die2 Die3 Die1GreaterThan3 Satisfied
1  1    1    1    0                0
2  2    1    1    0                1
3  3    1    1    0                1
4  4    1    1    1                1
5  5    1    1    1                1
6  6    1    1    1                1
7  1    2    1    0                1
8  2    2    1    0                1
9  3    2    1    0                0
10 4    2    1    1                0

<details>
<summary>▶️ Click to show the solution</summary>

```r
outcomes$Satisfied <- ifelse((outcomes$Die1 == outcomes$Die2 & outcomes$Die1 != outcomes$Die3) |
  (outcomes$Die2 == outcomes$Die3 & outcomes$Die1 != outcomes$Die3) |
    (outcomes$Die1 == outcomes$Die3 & outcomes$Die1 != outcomes$Die2), 1, 0)

# check we got it right
head(outcomes, 10)
```

</details>

##### **Question 1.3**

The sum of `Satisfied` is the number of possible ways for our event of interest to occur. Calculate the probability of observing the event.

<details>
<summary>▶️ Click to show hint</summary>

We can use `sum()` to sum up values, and `length()` to work out the total number of rows.

</details>

In [34]:
sum(outcomes$Satisfied)/length(outcomes$Satisfied)

[1] 0.4166667

<details>
<summary>▶️ Click to show the solution</summary>

```r
sum(outcomes$Satisfied)/length(outcomes$Satisfied)
```

</details>

#### **A "Smarter" Approach**

Sometimes, we avoid the brute-force approach — for example, when the sample space is too large for our computers to handle, when we lack the computational resources, or when the problem is simply too complex to solve this way.

##### **Question 1.4**
Calculate the probability of the event of interest (exactly two dice showing the same value) using probability rules. You can choose whether to do this using pen-and-paper or using R.

In [35]:
N = 6*6*6

pr1 = 6*5*4/N
pr2 = 6/N
1 - pr1 -pr2

[1] 0.4166667

<details>
<summary>▶️ Click to show the solution</summary>

Let E1 be the event that all 3 dice are different, and E2 be the case where all 3 dice are the same.
There are $6^3$ cases in total, in which $6 \times 5 \times 4$ cases are of event E1 and $6$ cases are of event E2.


```r
N = 6*6*6
Pr1 = 6*5*4/N
Pr2 = 6/N
1 - Pr1 - Pr2   # using the complement law
```

</details>

##### **Question 1.5**

Using the table from Question 1.3, calculate the probability of observing the event of interest by calculating `Pr1` and `Pr2`.

In [38]:
outcomes$AllDifferentNumbers = ifelse(outcomes$Die1 != outcomes$Die2 & outcomes$Die2 != outcomes$Die3 & outcomes$Die1 != outcomes$Die3, 1,0)
outcomes$AllSameNumbers = ifelse(outcomes$Die1 == outcomes$Die2 & outcomes$Die1 == outcomes$Die3, 1,0)

pr1 = sum(outcomes$AllDifferentNumbers)/length(outcomes$AllDifferentNumbers)
pr2 = sum(outcomes$AllSameNumbers)/length(outcomes$AllSameNumbers)

1- pr1 - pr2

[1] 0.4166667

<details>
<summary>▶️ Click to show the solution</summary>

```r
outcomes$E1 <- ifelse(outcomes$Die1 != outcomes$Die2 & outcomes$Die2 != outcomes$Die3 & outcomes$Die1 != outcomes$Die3, 1, 0)
outcomes$E2 <- ifelse(outcomes$Die1 == outcomes$Die2 & outcomes$Die2 == outcomes$Die3, 1, 0)

Pr1 = sum(outcomes$E1)/length(outcomes$E1)
Pr2 = sum(outcomes$E2)/length(outcomes$E2)

1 - Pr1 - Pr2
```

</details>

### **Question 2**
Assume a year with 365 days (i.e., non-leap year).

#### **Question 2.1**

What is the probability that two people share the same birthday (month and date; not year)?

<details>
<summary>▶️ Click to show the solution</summary>

The solution is most directly found by finding the probability that two people don’t share the same birthday and then use the property of complimentary events.

- Let $A$ be the event that two people share the same birthday
- Let $\overline{A}$ be the event that two people don’t share a birthday

There are $365 \times 365$ combinations of birthdays for two people, and $365 \times 364$ satisfy event $\overline{A}$. Thus,

$$\text{Pr}(\overline{A}) = \frac{365}{365}\times\frac{364}{365} = 0.9972603.$$

And, $\text{Pr}(A) = 1 - \text{Pr}(\overline{A}) = 0.0027397$.

In R, we can use the `prod()` function to compute the product of all elements of a vector.
```r
prod(364:365) == 364*365
prod(c(365, 365)) == 365^2
```

</details>

In [42]:
a = prod(364:365)
b = prod(c(365,365))

#probability of not sharing the birthday
c = a/b
#opposite of that:
1 - c

[1] 0.002739726

#### **Question 2.2**

Given that there are about 300 people enrolled in a particular unit, what is the probability that no one shares the same birthday?

<details>
<summary>▶️ Click to show hint 1</summary>

Let $\overline{A}$ be the event that no one shares the same birthday. Thus,

$$\text{Pr}(\overline{A}) = \frac{365}{365}\times\frac{364}{365}\times ⋯ \times \frac{365-300+1}{365}.$$

</details>

<details>
<summary>▶️ Click to show hint 2</summary>

If you use `prod(365:(365-300+1))`, you will very likely encounter overflow, meaning the number becomes larger than what your computer can handle. As a result, you might see the output `Inf` (infinity) in R.

A better approach is to compute a vector of **proportions** and then use `prod()` on that vector.

</details>

In [43]:
proportions <- (365: (365 - 200+1))/365
prod(proportions)

[1] 1.610126e-30

<details>
<summary>▶️ Click to show the solution</summary>

```r
prop = (365:(365-300+1))/365
prod(prop)
```

</details>



#### **Question 2.3**

What if there are 366 people enrolled in the unit?

<details>
<summary>▶️ Click to show the solution</summary>

Probability of no one sharing the same birthday is 0. To understand this, consider trying to assign everyone a unique day of the year. As the non-leap year has a maximum of 365 unique dates, the 366th person **must** share a birthday with someone else.

This is known as the **pigeon-hole principle**.

</details>

### **Question 3:**

A Covid-19 test has the following properties:

- If a person has Covid-19, the test correctly detects it 95% of the time.
- If a person does not have Covid-19, the test correctly shows a negative result 98% of the time.

In the population, 1% of people actually have the virus.

In [ ]:
# run the code to see a diagram
svgCode = paste(readLines("figures/bayes.svg", warn = F), collapse = "\n")
display_html(svgCode)

#### **Question 3.1**

If a randomly selected person is infected, what is the probability of testing positive?

<details>
<summary>▶️ Click to show the solution</summary>

Let $P$ be the event that a test is positive

Let $I$ be the event that a person is infected

From the information in the question, we can see that:

$$\Pr(P \mid I) = 0.95$$

This is what's called the "true positive rate".

</details>

#### **Question 3.2**

What is the probability of testing positive?

<details>
<summary>▶️ Click to show the solution</summary>

Here we are interested in determining the unconditional probabability $\Pr(P)$. We can calculate this using the law of total probability:

$$
\begin{align}
\Pr(P) &= \Pr(P|I)\times\Pr(I) + \Pr(P|\overline{I})\times\Pr(\overline{I}) \\
&= 0.95 \times 0.01 + 0.02 \times 0.99 \\
&= 0.0293
\end{align}
$$

</details>

#### **Question 3.3**

If a randomly selected person tests positive, what is the probability that the person actually has Covid-19?

<details>
<summary>▶️ Click to show hint</summary>

Recall Bayes' Theorem for conditional probability:

$$
\Pr(A \mid B) = \frac{\Pr(B \mid A) \times \Pr(A)}{\Pr(B)}
$$

</details>

<details>
<summary>▶️ Click to show the solution</summary>

Here we want to find $\Pr(I \mid P)$. We can obtain this via Bayes theorem:

$$
\begin{align}
\Pr(I \mid P) &= \frac{\Pr(P \mid I) \times \Pr(I)}{\Pr(P)} \\
&= \frac{0.95 \times 0.01}{0.0293} \\
&\approx 0.3242
\end{align}
$$

*Note that the **probability of being tested positive given being infected** tells you how good a test is at detecting infected patients. However, what we do care about in practice is **the probability of being infected given being tested positive**.*

*Many serious diseases have hallmark symptoms that almost always appear in patients who have the disease (i.e., almost 100% "true positive rate"). But those same symptoms can also appear in many other, less severe or more common illnesses. So, seeing the symptom alone isn’t enough to confidently diagnose the severe disease.*

***Examples***:

- *Chest pain: It’s a classic symptom of a heart attack (which can be life-threatening), but it’s also common in many less serious conditions like acid reflux, muscle strain, or anxiety.*
- *Fatigue: Seen in severe diseases like cancer or autoimmune disorders, but also in common conditions like sleep deprivation or stress.*

</details>

### **Question 4**

We have seen the classical definition of probability based on counting. There is another important (classical) definition — the frequentist definition — based on relative frequency. It defines the probability of an event as the limiting value of the proportion of times the event occurs as the number of trials becomes very large:

$$
\Pr(A) = \lim_{n \to \infty} \frac{N_A(n)}{n}
$$

where $N_A(n)$ is the number of times event $A$ occurs in $n$ trials.

We know that the probability of getting `Heads` (1) by tossing a fair coin is 0.5. Similarly, the probability of getting `Tails` (0) is 1 - 0.5 = 0.5. To simulate this coin tossing experiment `n` times, we could run `sample(0:1, size = n, replace = T)`.

In [ ]:
n = 10
x = sample(0:1, size = n, replace = T) #Head = 1; Tail = 0
print(x)
mean(x) #The relative frequency of Head

Assume that you want to toss a coin `n` times then calculate the relative frequency of `Heads` and repeat the process `nRepeats` times. To perform this experiment in R, we can do the following steps:

- Create an empty numeric vector of length `nRepeats` to store the frequency of `Heads`.

In [ ]:
nRepeats = 100
headFreqn10 = numeric(nRepeats) #Here, n = 10.

- We can use a `for` loop to repeat the process `nRepeats` times and save the results to `headFreqn10`.

In [ ]:
for(i in 1:nRepeats){ #Repeat for i varying from 1 to nRepeats
   x = sample(0:1, size = 10, replace = T) #Toss a coin 10 times
   headFreqn10[i] = mean(x) #Compute the relative frequency of `Head` in `x` and save the value to the i-th value in `headFreqn10`
}

#### **Question 4.1**

Follow the steps above to create new vectors named `headFreqn100`, `headFreqn1000`, and `headFreqn10000` that contain the relative frequencies of heads in 100, 1000, and 10000 tosses, respectively (repeated 100 times).

<details>
<summary>▶️ Click to show the solution</summary>

```r

nRepeats = 100
headFreqn100 = numeric(nRepeats)
headFreqn1000 = numeric(nRepeats)
headFreqn10000 = numeric(nRepeats)

for(i in 1:nRepeats){
   x = sample(0:1, size = 100, replace = T)
   headFreqn100[i] = mean(x)
}

for(i in 1:nRepeats){
   x = sample(0:1, size = 1000, replace = T)
   headFreqn1000[i] = mean(x)
}

for(i in 1:nRepeats){
   x = sample(0:1, size = 10000, replace = T)
   headFreqn10000[i] = mean(x)
}
```
</details>

#### **Question 4.2**

Group the simulated data in `headFreqn10`, `headFreqn100`, `headFreqn1000`, and `headFreqn10000` into a single data frame. Then, visualise the distribution of the relative frequency of heads for different numbers of coin tosses with boxplots. What observations can you make from the results? How do measures of central tendency and dispersion change?

<details>
<summary>▶️ Click to show the solution</summary>

```r
boxplot(headFreqn10, headFreqn100, headFreqn1000, headFreqn10000)
```

Notice that the measures of central tendency stay relatively constant as the number of trials increases. However, we see that the spread of the of the data reduces significantly as we perform more trials.
</details>

## **Workshop Questions**

# Your turn!
*The following questions are for you to practice, either individually or in small groups. Ask your tutor if you get stuck!*

### **Question 5**
- For any randomly selected card from a standard 52-card deck:
  - What is the probability that a player draws an ace?
  - What is the probability that a player draws a diamond?
- Are the events “player draws an ace” and “player draws a diamond” independent?
- Determine the probability of drawing an Ace of Diamonds from the deck.

<details>
<summary>▶️ Click to show the solution</summary>

Solution will be released at the end of the week!

</details>

### **Question 6**

A fair six-sided die is rolled 6 times. What is the probability that the product of all 6 outcomes is an odd number?

<details>
<summary>▶️ Click to show the solution</summary>

Solution will be released at the end of the week!

</details>

## **Question 7**

Sometimes there's no better option than using a brute-force method. Suppose a fair six-sided die is rolled 4 times, and the results are summed. Use a brute-force approach (as demonstrated earlier) to calculate the probability that the total sum is greater than 10.

<details>
<summary>▶️ Click to show the solution</summary>

Solution will be released at the end of the week!

</details>

## **Question 8**

You have two coins:
- One two-headed coin (always lands on `Heads`),
- One fair coin (`Heads` or `Tails` with equal probability).
You randomly select one of the two coins and flip it once.

**The result is Heads!!!**

What is the probability that you selected the two-headed coin?

<details>
<summary>▶️ Click to show the solution</summary>

Solution will be released at the end of the week!

</details>

## Question 9
A firm buys computers from three contractors—I, II, and III. Contractor I has a record of providing computers that contain 12\% defectives; Contractor II has a defective rate of 8\%; and Supplier III has a defective rate of 4\%. Suppose 35\%, 25\%, and 40\% of the current supply came from Contractors I, II, and III, respectively.

a)  If a computer is selected at random from this supply, what is the probability that it is defective?

b) If a randomly selected computer is defective, what is the probability that it came from Contractor II?

<details>
<summary>▶️ Click to show the solution</summary>

Solution will be released at the end of the week!

</details>

## Question 10
The company that owns WB Movie World, Sea World and Wet’n’Wild offers a 'VIP Pass' for 99 dollars that gives you unlimited entry into all 3 theme parks for 1 year. Now the company is considering offering this 'VIP Pass' for another year. However, managers are worried that there might be too many people who pay only once for the 'VIP Pass' while going to the theme parks very often. They decide that they will not offer the 'VIP Pass' for another year if the probability that a customer with a 'VIP Pass' goes to the parks more than 5 times is greater than 0.35. From the data of the current year they know:



> i) that the probability is 0.5 that a customer buying the 'VIP Pass' is 18 years or younger

> ii)  that the probability is 0.4 that a customer with a 'VIP Pass' is between 19 and 40 years of age

> iii) that the probability is 0.1 that a customer with a 'VIP Pass' is 41 years or older.

> iv) that the probability is 0.4, 0.3 and 0.2 that a 'VIP Pass' customer of age $\leq$ 18, age 18-40 and age $\geq$41, respectively, goes to the parks more than 5 times during the year.

a) Should they offer the 'VIP Pass' for another year?

b) What is the probability that a customer who goes to the parks more than 5 times is 18 years or younger?

<details>
<summary>▶️ Click to show the solution</summary>

Solution will be released at the end of the week!

</details>

## Question 11
The starship *Enterprise* is planning a surprise attack against the Klingons at 0100 hours. The chances of encountering a radiation storm, though, are causing Captain Kirk and Mr Spock to reassess their strategy. According to Spock’s calculations, the probability of the *Enterprise* encountering a severe radiation storm at 0100 hours is 0.6, a moderate storm, 0.3, and no storm, 0.1. Captain Kirk feels the probability of the attack’s being a success is 0.8 if there is a severe storm, 0.7 if there is a moderate storm, and 0.2 if there is no storm. Spock claims the attack would be a tactical misadventure if its probability of success were not at least 0.75. Should they attack?

<details>
<summary>▶️ Click to show the solution</summary>

Solution will be released at the end of the week!

</details>

## Question 12
For a particular word, denoted by $W$, a speech recognition device is 98\% reliable in recognising the word but also has a 5\% chance of misclassifying other words as this word. The word $W$ is a common word, with a 10\% chance of occurring

a) When the device says that the word $W$ occurs, what is the probability that it did occur?

b) The manufacturers of the above device wish to increase the probability in (a) to 0.8, by decreasing the probability of the device misclassifying other words as the word $W$. To what probability do they need to reduce the 5\% above in order to increase the probability in (a) to 0.8?

<details>
<summary>▶️ Click to show the solution</summary>

Solution will be released at the end of the week!

</details>